package com.michael;

import java.util.HashSet;
import java.util.Set;

// Generated 2014-3-9 10:15:13 by Hibernate Tools 3.4.0.CR1

/**
 * TbCatalog generated by hbm2java
 */
public class TbCatalog implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<TbGoods> goods;
	//private Set<TbGoods> goods = new HashSet();

	public TbCatalog() {
	}

	public TbCatalog(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/*public void addOneGoods(TbGoods oneGoods){
		this.goods.add(oneGoods);
	}
	
	public void removeOneGoods(TbGoods oneGoods){
		this.goods.remove(oneGoods);
	}
	*/
	public Set<TbGoods> getGoods(){
		return this.goods;
	}
	
	public void setGoods(Set<TbGoods> goods){
		this.goods = goods;
	}
}
