package com.michael;

// Generated 2014-3-9 18:06:58 by Hibernate Tools 3.4.0.CR1

/**
 * TbGoods generated by hbm2java
 */
public class TbGoods implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Float price;
	private String picturePath;
	private int catalogId;
	private TbCatalog catalog;

	public TbGoods() {
	}

	public TbGoods(String name, int catalogId) {
		this.name = name;
		this.catalogId = catalogId;
	}

	public TbGoods(String name, String description, Float price,
			String picturePath, int catalogId) {
		this.name = name;
		this.description = description;
		this.price = price;
		this.picturePath = picturePath;
		this.catalogId = catalogId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	public int getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(int catalogId) {
		this.catalogId = catalogId;
	}
	
	
	public TbCatalog getCatalog(){
		return this.catalog;
	}
	
	public void setCatalog(TbCatalog catalog){
		this.catalog = catalog;
	}
	
}
